### ISSUE TITLE
Store database credentials in the config file

### ISSUE THREAD

**Issue by Nuwini** [scorelab/Bassa#106]
Currently database credentials are hard coded to the `dbcon.py`
I suggest keeping them on a `.conf` file.
Further I think it's good to combine both current `.conf` files to a single one.

**Comment by rehrumesh** [comment]
Credentials should be moved to environment instead of storing in config files.

**Comment by Nuwini** [comment]
I will make the changes.

**Comment by kmehant** [comment]
I agree with @rehrumesh sir. So presently on `develop` branch, we are getting db credentials from environmental variables which is already implemented so closing this issue for now.
