### ISSUE TITLE
Redesign the Bassa signup page

### ISSUE THREAD

**Issue by yruwanmalee** [scorelab/Bassa#108]
The structure and the design of the sign up page needs more attention. I have redesigned the sign in page and I am planning to redesign thr signup accordingly to provide the consistency of the UI.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by yruwanmalee** [comment]
@rehrumesh A user's name is not included in the sign up form. Is there any special reason?

**Comment by kmehant** [comment]
We are shifting Bassa UI from Angular to React and will have all this covered there as part of GSoC 2019 so closing this for now.
