### ISSUE TITLE
Back-end unit tests

### ISSUE THREAD

**Issue by rajikaimal** [scorelab/Bassa#112]
This thread will be used for tracking issues related to back-end testing. 

> Work in progress !!!

**Comment by saisankargochhayat** [comment]
I will be adding some unit tests shortly.

**Comment by rajikaimal** [comment]
Can you mention which functionalities you're testing. I'm working on testing REST API functionality.
So basically I'm working on testing functionality specified in `components/core/REST.py`

**Comment by saisankargochhayat** [comment]
@rajikaimal I was thinking of working on tests for signup , login , and approve functions in REST.py .

**Comment by rajikaimal** [comment]
Cool ! :+1:

**Comment by saisankargochhayat** [comment]
We should make a branch and work on it together :) @rajikaimal

**Comment by rajikaimal** [comment]
@saisankargochhayat I was thinking the same.

**Comment by rajikaimal** [comment]
Did you implemented anything yet ? or shall I add mine, so that you can start on top of it.

**Comment by saisankargochhayat** [comment]
that would be great :+1: , you can add yours we will start working upon it.

**Comment by kmehant** [comment]
So
* We got tests for UI and API by @iammosespaulr 
* I have done load testing using locust framework and documented it here https://bit.ly/2ElDJYr 
I would close this issue as it's very old and things have been achieved 😃
