### ISSUE TITLE
Downloads in the Bassa server fails

### ISSUE THREAD

**Issue by rehrumesh** [scorelab/Bassa#117]
When bassa try to download multiple files, it crashes the app,

## Expected Behavior
Bassa should be able to handle concurrent downloads without any issues.

## Current Behavior
If there are multiple downloads, server crashes.

## Possible Solution
Remove the stat module.

**Comment by saisankargochhayat** [comment]
I will work on this , to find the exact cause , then fix it . @rehrumesh

**Comment by saisankargochhayat** [comment]
On increasing the threadpool and updating SQLAlchemy versions , the multiple download seems to work fine. Will try this a few more times and make a PR .

**Comment by vivonk** [comment]
I guess the issue is resolved and download is even working fine on the queue of 20+ links. 
Closing the issue. Further, if anyone wants to reopen, the issue would be around the same thing.
