### ISSUE TITLE
Add all the configurations to a single conf file

### ISSUE THREAD

**Issue by paarandika** [scorelab/Bassa#124]
## Expected Behavior
We need to implement a method to add all the configs to a single file (or multiple files to make things more clear) and fetch them from there. These conf file(s) should be in JSON or YAML format. Preferably with a web UI for admins to do the configs.

## Current Behavior
Currently, a number of configurations which are vital to the system are scattered all over the code and it is hard to keep track of them. 

## Possible Solution
Use the existing ConfReader class and extend it to support all the configurations.

**Comment by vivonk** [comment]
@paarandika can you point out the configurations you were talking about? I am just aware of the `email.conf` and `dl.conf`

**Comment by kmehant** [comment]
@paarandika 
Presently on `develop` branch, We have got a working confReader which serves two configuration files to Bassa API server. These configurations are in JSON form too. So closing this issue for now. Please mention any points which I missed out.
