### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by rehrumesh** [scorelab/Bassa#132]

**Comment by Menuka5** [comment]
I would like to work on this issue.

**Comment by rehrumesh** [comment]
great. looking forward for a PR.

**Comment by malithsen** [comment]
#235

**Comment by kmehant** [comment]
So We have got Contributing Guide for Bassa Here [Link](https://github.com/scorelab/Bassa/blob/master/CONTRIBUTING.md)
