### ISSUE TITLE
Making ReadMe file more comprehensive

### ISSUE THREAD

**Issue by Nuwini** [scorelab/Bassa#138]
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by agentmilindu** [comment]
IMO, We should remove the API documentation part from the README.md. That should go to a separate Wiki document and be accompanied by an [OpenAPI-Specification](https://github.com/OAI/OpenAPI-Specification).

**Comment by kmehant** [comment]
I think we have got API endpoints defined now in the Wiki and I am working on documentation site will be adding proper API documentation for our server too. So will close this for now.
