### ISSUE TITLE
Bassa Wiki  should be improved

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#139]
Bassa Wiki Home should be about Bassa, not about PWAs. `README.md` has stuff which mainly targets a developer( API endpoints, etc ) and might frustrate a user. The wiki should have a "How to install" guide. etc from a user's perspective. 

## Current Behavior
Currently, the wiki has nothing about Bassa but an article on PWA. 

## Possible Solution
Should create wiki pages as follows.
- [ ]  How to install guide 
  - [ ] On Windows
  - [ ]  On Linux
  - [ ]  On MacOS
- [ ]  How to use guide
- [ ]  Troubleshoot guide.

**Comment by agentmilindu** [comment]
@malithsen @rehrumesh I guess we can divide this issue into several tasks. 

1. How to install on Windows guide
1. How to install on Linux guide
1. How to install on MacOS guide
1. How to use guide
1. Troubleshoot guide.

**Comment by iammosespaulr** [comment]
I would like to do the linux part

**Comment by rmddcr** [comment]
I would like to do macOS part
