### ISSUE TITLE
Bassa

### ISSUE THREAD

**Issue by Warrrior2017** [scorelab/Bassa#232]
The wiki should have a "How to install" guide.
At the moment,the wiki has nothing about Bassa,but on the wiki is an article on PWA.
My solution is to create a "How to install" guide for Bassa.

**Comment by malithsen** [comment]
Hi @Warrrior2017 
Wiki already has installation guides for [Linux](https://github.com/scorelab/Bassa/wiki/Linux-Installation-Guide) and [Windows](https://github.com/scorelab/Bassa/wiki/Windows-Installation-Guide)
However as you have noticed the home page points to an article on PWA which should be moved somewhere else
