### ISSUE TITLE
New Feature Idea

### ISSUE THREAD

**Issue by shravyanandyala** [scorelab/Bassa#233]
An idea for Bassa would be to have the admin be able to view the "normal people" accounts that have the most activity. This way, even if downloads are not necessary inappropriate, the admin can still see who is misusing resources. This could be integrated with the admin's interface for dealing with inappropriate downloads so that there is an automatic response to warn or disable the account of the person downloading more than necessary.

**Comment by malithsen** [comment]
Hi @shravyanandyala this feature has already been implemented in the admin dashboard. Currently it shows the pie chart of the download sizes of each user.

**Comment by shravyanandyala** [comment]
Oh, I see it now. I must have missed it before. Thanks for letting me know!
