### ISSUE TITLE
`sudo`  in `setup.sh` making problems in Docker

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#245]
Docker runs the setup.sh file as root and having problems with `sudo` commands as `sudo` is not available in `root` user. This makes the setup.sh not usable in docker image creation. What can we do?

**Comment by malithsen** [comment]
We can change the setup.sh to check if it's running as root and change the commands accordingly

**Comment by agentmilindu** [comment]
@malithsen What you think of the apporach used in https://github.com/scorelab/Bassa/pull/690 ?

**Comment by malithsen** [comment]
@agentmilindu Made few comments. Let's continue the discussion there

**Comment by kmehant** [comment]
This is fixed so closing the PR 😄
