### ISSUE TITLE
docker-compose.yml to run Bassa

### ISSUE THREAD

**Issue by kmehant** [scorelab/Bassa#248]

**Comment by agentmilindu** [comment]
We will have 4 major containers for this, 

1. api ( `components/core/Dockerfile` )
2. ui ( ui/Dockerfile )
3. mysql
4. area2

Right @malithsen, @rehrumesh ?

**Comment by rehrumesh** [comment]
Actually, it is three. area2 was bundled with the API.

**Comment by agentmilindu** [comment]
Can we decouple `aria2`? If we want to replace `aria2` with something better, then it would be easy for us, right? On the other hand, can we spawn more `aria2` instances when there is huge load and get more work done? I'm not much familiar with Bassa core.

**Comment by agentmilindu** [comment]
I now feel breaking the UI and API was not necessary and it add too many complications. Shall we merge the two into one Docker? @rehrumesh @malithsen @kmehant

**Comment by kmehant** [comment]
Integrated docker-compose for all the four components :)
