### ISSUE TITLE
Generate .gitignore using gitignore.io

### ISSUE THREAD

**Issue by tintinmovie** [scorelab/Bassa#255]
(GCI 2017 Task: [https://codein.withgoogle.com/tasks/4997285060542464/](https://codein.withgoogle.com/tasks/4997285060542464/))

Technologies identified to use in gitignore.io are: C, Node and Visual Studio Code

**Comment by agentmilindu** [comment]
Nice! You are good to go. Let's generate the `.gitignore` file with the above discussed technologies.

**Comment by malithsen** [comment]
Why C?
Include Python, Vim and Sublime 

Also the following entries from current `.gitignore`
```
*.log
components/core/debug-server.log
downloads/

# UI
ui/dist
ui/node_modules
ui/app/lib
```

**Comment by tintinmovie** [comment]
I choose C because in the current .gitignore file, there are entries for Object files (eg  ".o"  , " .obj") Apparently these are files are created while using C.  I may be wrong though.

**Comment by malithsen** [comment]
Since C hasn't been used anywhere in the Bassa, let's remove it. Let's keep the vscode entry
