### ISSUE TITLE
Add detailed instructions on how to use dockers to build Bassa

### ISSUE THREAD

**Issue by kmehant** [scorelab/Bassa#257]
Currently, we have two Dockerfiles to spin up two different containers for Bassa frontend and backend. 

There is a pull request( #249) on docker-compose to spin up all the containers for Bassa UI, Core and MySQL, the work is in progress. To encourage easy usage and build of Bassa project, we need to update the `README.md`.

**Comment by agentmilindu** [comment]
@kmehant I think the current `docker-compose.yml` is targetting the developers, to help developers to develop  Bassa and run it with one command. Thus, this should go to Developer Guide wiki.

 Let's describe how to run the `docker-composer.yml` providing the needed environment variables, in a beginner-friendly manner.

**Comment by kmehant** [comment]
@agentmilindu I will work on it. Will send a pull request shortly
