### ISSUE TITLE
Failed to import the database

### ISSUE THREAD

**Issue by azisnaufal** [scorelab/Bassa#260]
I have create a db named "Bassa".
And I want to import the database that Bassa provided before.
Then I got this error message : 
`ERROR 1452 (23000) at line 109: Cannot add or update a child row: a foreign key constraint fails (Bassa.#sql-7646_5, CONSTRAINT rate_ibfk_2 FOREIGN KEY (id) REFERENCES download (id))`

I have been fix this issue, I will send a PR ASAP.

**Comment by vivonk** [comment]
@azisnaufal I guess it's because when you created a Bassa database from command then properties was written before and now it's trying to override. Can you tell in more detail about what is wrong with this specific?

**Comment by vivonk** [comment]
Oh that's nice @azisnaufal. @agentmilindu can we close this issue?
