### ISSUE TITLE
Should get SECRET_KEY from a Config file

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#321]
https://github.com/scorelab/Bassa/blob/ef497a351b36e78ef6764e2da5c06dae6e413a93/components/core/REST.py#L19

**Comment by rehrumesh** [comment]
https://github.com/scorelab/Bassa/blob/1294190d79cc00f98e0579455564634ac858b015/components/core/Server.py#L19

**Comment by vivonk** [comment]
@rehrumesh It has been resolved with #475 in https://github.com/scorelab/Bassa/blob/2db2841f0ad0b013e26c5a841c7447c762d663cb/components/core/utils/app_constants.py so can we close this?
Branch - Develop

**Comment by agentmilindu** [comment]
Fixed in https://github.com/scorelab/Bassa/pull/475
