### ISSUE TITLE
Breakdown REST.py into manageable subparts

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#324]
I think we should break the `REST.py` into several parts as following,

Rename REST.py into Server.py
Create a directory as Routes/ and put an `index.py`
Create a User.py in `Routes` and add all the User related routes there.
Create a Download.py in `Routes` and add all the Download related routes there.
etc. 

And finally, import all these Route files in `Routes` directory into `index.py` and then import this Routes into new `Server.py`

**Comment by vivonk** [comment]
@agentmilindu  is this issue still pending? I would like to work on this

**Comment by agentmilindu** [comment]
Hmm, check the currently open PR(https://github.com/scorelab/Bassa/pull/400) by Padam. He introduces some changes, which might break the UI. Thus we have to change the UIs accordingly. if you can work on that PR and improve it to get th UIs, etc also working, that would be awesome! 

@padamchopra Can you enlightn us on this? 
@rehrumesh @malithsen

**Comment by padamchopra** [comment]
@agentmilindu @vivonk , what I've done is that I've changed the code to give the response in the following way-
```
{ "status" : 200 } //success
{ "status" : 400 } //error
```

Earlier it was in the following way-
```
{ "status" : 200 } //success
{ "error" : 400 } //error
```
Due to this change in the response structure, the frontend might break. What I've done is the correct way for responses, so before merging the PR, the UI must also be worked upon

**Comment by vivonk** [comment]
Bassa codebase has been refactored a lot so this issue is resolved now. @agentmilindu
