### ISSUE TITLE
Replace print statements with logging

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#325]
I see a lot of `print` statements while we have a proper logging mechanism configured in the code. We should replace all these `print` commands with `logger`

**Comment by vivonk** [comment]
@agentmilindu I can see some `print` statements in Download related python files. Does these print statements should be logged ? I would like to work on this

**Comment by agentmilindu** [comment]
I see no reason to `print` anything, need to change to use loggers.  

@malithsen @rehrumesh

**Comment by surana-mudit** [comment]
@agentmilindu  @vivonk  I would like to work on this issue. Can you please help me in getting started with it.

**Comment by vivonk** [comment]
@surana-mudit thanks for showing your interest. You can start with checking the print statement in the backend code, `component/core`, and change that with logger info/warning/error respectively. For reference how logger is configured, check in `Main.py` and [here](https://docs.python.org/3/library/logging.html)

**Comment by surana-mudit** [comment]
![before](https://user-images.githubusercontent.com/26516997/46176855-6ba7a300-c2ce-11e8-9dc9-ce752ceee9fd.png)
![after](https://user-images.githubusercontent.com/26516997/46176856-6ba7a300-c2ce-11e8-9cdb-8f7e88cb713f.png)
I have done these changes in the `DiskMan.py` file of `components/core`.
Are these fine ? Should I do this in the other files?

**Comment by vivonk** [comment]
You don't need to configure it again. Once you configure logger, by default it will get things on the way.
Remove all configuration like
`basicConfig()`
Just use `logging.warning()`

**Comment by surana-mudit** [comment]
okk so I don't have to use `basicConfig()` and `check_conf_availability()` in each and every file, just have to write the info/warning/error instead of print ?
