### ISSUE TITLE
Wrong spelling in signup window for 'confirmation'

### ISSUE THREAD

**Issue by iammosespaulr** [scorelab/Bassa#332]
Wrong Spelling 

## Context
 This issue affects user readability
the spelling for confirmation is wrong 
* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):cyborg hawk
* Link to your project:
![screenshot from 2017-12-25 14 30 11](https://user-images.githubusercontent.com/28682735/34339333-dda10a7e-e998-11e7-892d-c60ebd28272b.png)

**Comment by vivonk** [comment]
Yes @rkpattnaik780 now view looks like this
![image](https://user-images.githubusercontent.com/25587962/41813374-86882bc6-7752-11e8-96b5-123b8908c5e6.png)
