### ISSUE TITLE
Add PyPi version badge to the README.md

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#34]
Add PyPi version badge to the  README.md from some badge providor. 

![image](https://cloud.githubusercontent.com/assets/1391468/20645566/1af2b496-b488-11e6-931d-fd56e4ce4cf3.png)

**Comment by agentmilindu** [comment]
Eg : https://shields.io

**Comment by uk175** [comment]
Hi!

I just noticed that the PyPi version badge is already there in the README file, so is there a reason to why this issue is still open?

**Comment by malithsen** [comment]
@uk175 Thanks for the heads up :)
