### ISSUE TITLE
Add Bassa logo to dashboard

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#347]
![image](https://user-images.githubusercontent.com/1391468/34372162-f0474ae2-eaf8-11e7-8d5b-2cb3ba331a8c.png)

Replace he above text in Dashboard with Bassa logo.

**Comment by iammosespaulr** [comment]
I added the wrong file by mistake and had it fixed just now

**Comment by iammosespaulr** [comment]
@agentmilindu this has been done

**Comment by iammosespaulr** [comment]
https://github.com/scorelab/Bassa/pull/434

**Comment by iammosespaulr** [comment]
![screenshot from 2018-02-19 18-06-50](https://user-images.githubusercontent.com/28682735/36378287-447bb7ca-15a0-11e8-9af5-dd14e6c802e4.png)

**Comment by iammosespaulr** [comment]
@malithsen

**Comment by rkpattnaik780** [comment]
Is this issue still open?

**Comment by agentmilindu** [comment]
Fixed by #434
