### ISSUE TITLE
Check user type and show/hide admin menu

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#348]
![image](https://user-images.githubusercontent.com/1391468/34372232-4d4fecbc-eaf9-11e7-8a4a-0b3df586070d.png)

Show or hide the Admin menu depending on the user type. Only Admin level users should see it.

**Comment by tanmayanand44** [comment]
@agentmilindu .Can you please guide me a little to resolve this issue.

**Comment by agentmilindu** [comment]
@malithsen will be you mentos for this issue :)

**Comment by tanmayanand44** [comment]
Ok thanks.

**Comment by tanmayanand44** [comment]
@malithsen Sir,guide me how to proceed.

**Comment by malithsen** [comment]
Hi @tanmayanand44 
There are 2 user types on Bassa. 

1. Regular users
2. Admins

Admin  menu option in the side panel should only be visible to the admins. Currently it is shown to all users but only admins are allowed to view its content

**Comment by agentmilindu** [comment]
@malithsen is some property set in user object to identify the user level? Where should he look for this?

**Comment by malithsen** [comment]
`UserService.getAuthLevel()` will return the logged in user's auth level. 


**Auth levels** - https://github.com/scorelab/Bassa/wiki/URL-Endpoints#post
ADMIN - 0
USER - 1

**Comment by malithsen** [comment]
@tanmayanand44 @agentmilindu https://github.com/scorelab/Bassa/blob/bb455d083553da38c95e9e548bb6f77354d91755/ui/src/app/index.js#L119

This is how current functionality has been implemented. Not so neat

**Comment by tanmayanand44** [comment]
@malithsen Problem is that in Bassa/ui/src/app/components/services/NavService.js  all these 3 object items are being sent.We can control them then it's done.

function navService($q){
    var menuItems = [
      {
        name: 'Dashboard',
        icon: 'dashboard',
        sref: '.dashboard'
      },
      {
        name: 'Completed',
        icon: 'view_module',
        sref: '.table'
      },
      {
        name: 'Admin',
        icon: 'person',
        sref: '.admin'
      },
    ];

**Comment by malithsen** [comment]
`navService.loadAllItems()` is used by `MainController`, you can filter the items there based on role 
https://github.com/scorelab/Bassa/blob/bb455d083553da38c95e9e548bb6f77354d91755/ui/src/app/controllers/MainController.js#L19-L23

**Comment by tanmayanand44** [comment]
@malithsen @agentmilindu I have created a PR #365. Please review it thoroughly as it is major feature and ping me for any suggestion.

**Comment by tanmayanand44** [comment]
@malithsen @agentmilindu I have created a PR #365. Please review it thoroughly as it is major feature and ping me for any suggestion.

**Comment by tanmayanand44** [comment]
@agentmilindu @malithsen I am experiencing a bug from my recently made PR #365.The first time we open up the login page and get logged in,it successfully shows menu items (admin removed for non-admin users) but again if we login then only admin menu is being shown for non-admin users.May this is due to Bassa progressive nature.This isssue gets resolved if we refresh login page and then login.
Please guide.
