### ISSUE TITLE
Restyle the User menu

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#349]
![image](https://user-images.githubusercontent.com/1391468/34372292-b0332a74-eaf9-11e7-917a-6a47edd61550.png)

Let's style this menu better way. 

The menu should have a top part with user's details, name and thumbnail maybe. 
Then should be the Log Out, Setting, etc menu items.

**Comment by tanmayanand44** [comment]
Created PR #373.Please review.
