### ISSUE TITLE
Better confirmation dialogs

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#350]
![image](https://user-images.githubusercontent.com/1391468/34372343-f4bcb4a8-eaf9-11e7-9159-91a74b658d36.png)

Let's use some UI plugins to show some nice confirmation dialogs.

**Comment by tanmayanand44** [comment]
@agentmilindu I wish to work on this.

**Comment by agentmilindu** [comment]
@tanmayanand44 Nice, suggest a good UI library for showing Dialog boxes. Work with @malithsen and @rehrumesh on this.

**Comment by tanmayanand44** [comment]
@agentmilindu @malithsen @rehrumesh We can use jQuery.

**Comment by agentmilindu** [comment]
@malithsen Are we using Angular Boilerplate? 

@tanmayanand44 If yes, check, there could be some Dialog box plugins especially for Angular Bootstrap.

**Comment by vivonk** [comment]
I would like to work on this, as @tanmayanand44 is not working, I think
