### ISSUE TITLE
Show a dialog to the user if the session has expired. 

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#351]
Show some kind of a dialog to the user saying the session has expired at least when a new request is sent to the API and gets a 403 forbidden response.

**Comment by vivonk** [comment]
@agentmilindu can I work on this or any issues which are labeled with `GoogleCodeIn`?

**Comment by agentmilindu** [comment]
@vivonk yes, you can work on this

**Comment by vivonk** [comment]
One more thing that should we consider only 403 or anything apart from 200. @agentmilindu

**Comment by agentmilindu** [comment]
@vivonk Yes, anything apart from 200 should be handled, but when it is 403, we should mention it explicitly  and ask the user to log in.
