### ISSUE TITLE
MySQLdb does not support python3

### ISSUE THREAD

**Issue by iammosespaulr** [scorelab/Bassa#354]

**Comment by agentmilindu** [comment]
@iammosespaulr Can you elaborate it a little? Maybe the errors you get.

**Comment by iammosespaulr** [comment]
@agentmilindu. Yeah sure you have suggested to use python 3 in the readme but in order to use MySqldb one must not use python 3 as pip3 cannot be used to install MySqldb due to compatibility issues

**Comment by malithsen** [comment]
Um I'm not sure I understand the issue correctly. Is it documented somewhere in Bassa to install mysql through pip?
pip cannot and should not be used to install anything other than python packages. It should be installed through the distro's package manager.

**Comment by iammosespaulr** [comment]
Yeah you’re right the documentation is faulty

**Comment by malithsen** [comment]
Could you please point where on the documentation it is instructed to install mysql through pip

**Comment by JaDogg** [comment]
Related: https://stackoverflow.com/questions/4960048/python-3-and-mysql

**Comment by malithsen** [comment]
`mysqlclient` will be installed when you run `python setup.sh develop`.

**Comment by kmehant** [comment]
@iammosespaulr 
`Mysqldb` not taking in the literal sense seems to be a python package is installed by this command as necessary for making db connections.   
```
python3 setup.py develop
```
And I suppose should work on updated `develop` branch. So I am closing this issue for now.
