### ISSUE TITLE
Missing "use strict" statement

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#36]
When you send PRs regarding fixes for missing "use strict" statement, refer this issue! You can find the Lint errors from the following.

https://www.bithound.io/github/scorelab/Bassa/master/files#lint

**Comment by coderaashir** [comment]
So on adding 'use strict' to adminCtrl.js, 
bitHound gives many more errors than before. (And these are legit errors in the js! (Missing semi-colon, strings must have single quotes, etc. ) 
I have attached a screenshot. Should i still make a PR?

**Comment by malithsen** [comment]
closing #58
