### ISSUE TITLE
BASSA ISSUE

### ISSUE THREAD

**Issue by Yash2356** [scorelab/Bassa#367]
Wrong Spelling
Context
This issue affects user readability
the spelling for confirmation is wrong

Version used:
Environment name and version (e.g. Chrome 39, node.js 5.4):
Operating System and version (desktop or mobile):Ubuntu 16.04 (virtual machine)
Link to your project:

**Comment by iammosespaulr** [comment]
Hey this is just wrong , you not only copied my picture but you even went to the the extent of replicating my own issue

**Comment by Yash2356** [comment]
SORRY FOR THAT I DO NOT KNOW THAT BY MISTAKE I COPY THIS.

**Comment by Yash2356** [comment]
I WROTE THIS MY SELF YOU THOUGHT THAT YOUR CONTENT AND MY CONTENT IS SAME BUT I CHANGE IT NOW SO YOU ARE HAPPY WITH IT.AGAIN SORRY FOR THAT BY MISTAKE IT HAPPENS.

**Comment by Yash2356** [comment]
Thanks for it.

**Comment by malithsen** [comment]
Hi @Yash2356,
I appreciate your enthusiasm to contribute. However plagiarism is unacceptable and SCoRe as an organization highly discourages you from attempting so.

**Comment by Yash2356** [comment]
I am so sorry! for this kind of misbehave i will never do this again.Please sorry.
