### ISSUE TITLE
Documentation for Windows users needs improvements (GCI)

### ISSUE THREAD

**Issue by shlokj** [scorelab/Bassa#370]
In places where Linux commands are used, windows users face difficulties. For example in "sudo python setup.py develop" it should be mentioned that sudo signifies admin usage, and for Windows users they should run their CMD as administrator.

**Comment by agentmilindu** [comment]
@shlokj I agree on this.

**Comment by tintinmovie** [comment]
Maybe update the readme.md linking to the Windows Installation Guide wiki page?

**Comment by kmehant** [comment]
This is solved and closing this as we have a separate guide for Windows
