### ISSUE TITLE
Incorrect Credential error and Admin privileges

### ISSUE THREAD

**Issue by padamchopra** [scorelab/Bassa#377]
## Update:: Checkout the conversation thread below for the updated issue.
```
Previous Issue-
Running Main.py requires multiple modules, a list should be made available for the user to download them all at once or maybe include the commands to install them in setup.sh. Due to the modules not being downloaded at once, the user has to carefully look out in the error message thrown while trying to run Main.py and then google about the installation instruction for the missing module. Automating it will help in making the overall installation process for Bassa easier

Some of the modules required
flask.cors.ext, flask.socket_io, mysqldb, sqlalchemy, websocket, websocket-client
```

**Comment by malithsen** [comment]
all these are installed through requirements.txt when you run `python setup.py develop`

**Comment by padamchopra** [comment]
# Update 
As @agentmilindu told me, all the requirements can be installed using `pip3 install -r requirements.txt` 
Requirements.txt is saved in components/core. So I would like the instruction for this to be added to the readme setup instructions

**Comment by malithsen** [comment]
https://github.com/scorelab/Bassa/blob/a94be85b8dc39fa7d023cb23f57ba2555b58d7a4/components/core/setup.py#L19

**Comment by agentmilindu** [comment]
@malithsen @padamchopra Can we check if all these get installed when running `python setup.py develop`. It seems some are facing problems.

**Comment by padamchopra** [comment]
Yes, I think the error here was- I ran this command using `python setup.py develop` But I started main.py using `python3 main.py`. Can this be the reason for the error?

**Comment by malithsen** [comment]
Could be if 'python' refers to `python2`

**Comment by padamchopra** [comment]
Then I guess it is totally my fault (really embarassed). But here's another issue I found- 
On incorrect credentials- I get two popups for error, I think only one should be given 
![error](https://user-images.githubusercontent.com/19776024/34468201-c205fe28-ef29-11e7-8747-42141bf1031f.png)

**Comment by padamchopra** [comment]
## A second issue
Since the entire Bassa has realtime screen changes in response to user actions, I think when we approve the user, the request should disappear from the screen on the same time. But it still stays till I refresh-
![screenshot from 2018-01-01 19-28-58](https://user-images.githubusercontent.com/19776024/34468213-2d024db2-ef2a-11e7-98e0-97781532d3b2.png)
**Another suggestion** 
 think it is necessary that the admin should be able to invoke the access of a user after approving them. There should be a section in which the admin can see the users that he has approved till now and disapprove them as well

**Comment by agentmilindu** [comment]
@padamchopra Shall we create a new issue for this and close this issue?

**Comment by padamchopra** [comment]
@agentmilindu Ok

**Comment by malithsen** [comment]
Duplicate credentials has been fixed https://github.com/scorelab/Bassa/commit/5c8053f3fe8c264fbc65c6257f023a5008cca76e

Second one would be a feature request. Related #341

**Comment by malithsen** [comment]
@padamchopra @agentmilindu We can test whether all the python dependencies get installed by
1. Create a new virtualenv in components/core. `virtualenv -p /usr/bin/python3 bassa`
2. `source bassa/bin/activate`
3. Install dependencies `sudo python setup.py develop`
4. Check if everything has been installed `pip freeze`
