### ISSUE TITLE
Incorrect Credentials message and admin tab issues

### ISSUE THREAD

**Issue by padamchopra** [scorelab/Bassa#379]
## Incorrect Credentials error message
On entering incorrect credentials- I get two popups for error, I think only one should be given

![error](https://user-images.githubusercontent.com/19776024/34468324-378f282a-ef2c-11e7-9aa0-387457983761.png)

## Real-time update on approving user
Since the entire Bassa has real-time screen changes in response to user actions, I think when we approve the user, the request should disappear from the screen on the same time. But it still stays till I refresh

![screenshot from 2018-01-01 19-28-58](https://user-images.githubusercontent.com/19776024/34468322-29845d86-ef2c-11e7-8369-e4b4ea55de76.png)

## Another Suggestion
I think it is necessary that the admin should be able to invoke the access of a user after approving them. There should be a section in which the admin can see the users that he has approved till now and disapprove them as well

**Comment by padamchopra** [comment]
Update: The incorrect login credential error was fixed with commit `5c8053f` by @malithsen

**Comment by iammosespaulr** [comment]
@agentmilindu This has been fixed ..
