### ISSUE TITLE
Bassa Bug And Improvement Methods

### ISSUE THREAD

**Issue by demonsingh336** [scorelab/Bassa#380]
Expected Behavior = When We Try To Code In git using there repository.. and clone the 
bassa it should automatically recognise the user if he or she has signed in the particular
oprating machine.(it can be mobile or computer)

Current Behavior = Its Current behaviour is that, that it sometimes does not recognise the user
even if he is has signed in in the computer.

Possible Solution = Possible Solution can only be handled by some specific person 
how has masters in handling the technical problems of the data base.

## Steps to Reproduce (for bugs)
1.Open Git
2. Clone The Bassa Repository
3.After that while performing codings of treasure and cherry picking we enter the commands
4.We ahould get easily be recognised and we haven't tp do it by ourself

## Context
When i was performing my gci task it affect me because i was unable to get recognized
which led me into a problem..
i have to do my recognizeation by my self.. which caused me the problem.

## Your Environment
Chrome In Computer
* Operating System and version Desktop and Windows 10.1

**Comment by agentmilindu** [comment]
I guess this is a problem with Git, not Bassa.

**Comment by demonsingh336** [comment]
No Its Even With bassa... My explainatoin us not up to the mark but the bug is quite 
similar

**Comment by kmehant** [comment]
@demonsingh336 I think you might have some issue in setting up git workspace for Bassa. Try logging in before you do anything, Check whether your origin and upstream is setup properly and both are in sync. Hope it works for you so closing this for now.
