### ISSUE TITLE
sqlalchemy.exc.InvalidRequestError: This connection is closed

### ISSUE THREAD

**Issue by iammosespaulr** [scorelab/Bassa#381]
The solution varies from distro to distro but for problems like this

![screenshot from 2018-01-01 20-35-59](https://user-images.githubusercontent.com/28682735/34470126-d232cac6-ef3b-11e7-84b1-42f2370de352.png)

You've got to add your credentials to the DBCon.py. Sample code for DBCon.py is as follows 

```
import MySQLdb
import os

_db=None


def get_db_con () :
    global _db
    if _db==None:
        try:
            _db=MySQLdb.connect(user="TYPE_YOUR_USERNAME",passwd="TYPE_YOUR_PASSWORD",db="Bassa")
            return _db
        except:
            return None
    else:
        return _db

def close_db_con () :
    if _db!=None:
        _db.close()
```

**Comment by iammosespaulr** [comment]
The solution varies from distro to distro but for problems like this ----> 
![screenshot from 2018-01-01 20-35-59](https://user-images.githubusercontent.com/28682735/34470126-d232cac6-ef3b-11e7-84b1-42f2370de352.png)
The solution is rather simple ...
You've got to add your credentials to the DBCon.py
my sample code for DBCon.py is as follows 
import MySQLdb
import os

_db=None


def get_db_con () :
    global _db
    if _db==None:
        try:
            _db=MySQLdb.connect(user="TYPE_YOUR_USERNAME",passwd="TYPE_YOUR_PASSWORD",db="Bassa")
            return _db
        except:
            return None
    else:
        return _db

def close_db_con () :
    if _db!=None:
        _db.close()

**Comment by agentmilindu** [comment]
You can either change the values in `DBCon.py` as above or if you have latest codes with you, set the database credentials as environment variables. But check if your `DBCon.py` has the following line. 
```
MySQLdb.connect("db", os.environ.get('BASSA_DB_USERNAME'), os.environ.get('BASSA_DB_PASSWORD'), os.environ.get('BASSA_DB_NAME'))
```

If yes, then set these environment variables with your DB details. 
1. BASSA_DB_USERNAME
2. BASSA_DB_PASSWORD
3. BASSA_DB_NAME

If you are on Linux, you can do this like `export BASSA_DB_NAME=bassa` likewise.

**Comment by iammosespaulr** [comment]
@agentmilindu Exactly

**Comment by vivonk** [comment]
@agentmilindu is it should be added to the `README.md ` as it is the general issue that users/developers will face. Also, can be added to troubleshoot wiki

**Comment by vibhavagarwal5** [comment]
`MySQLdb.connect("db", os.environ.get('BASSA_DB_USERNAME'), os.environ.get('BASSA_DB_PASSWORD'), os.environ.get('BASSA_DB_NAME'))
` doesn't work

`            _db=MySQLdb.connect(user="TYPE_YOUR_USERNAME",passwd="TYPE_YOUR_PASSWORD",db="Bassa")
` worked for Mac and linux Mint

**Comment by iammosespaulr** [comment]
It will work only when you export the variables @vibhavagarwal5

**Comment by vibhavagarwal5** [comment]
Tried that but didn't work out.

**Comment by vivonk** [comment]
@agentmilindu can we write it in documentation and close it here?

**Comment by kmehant** [comment]
Guidelines for making proper database connection from Bassa API server  have been added to [README.md](https://github.com/scorelab/Bassa/blob/develop/README.md).
So closing this issue.
