### ISSUE TITLE
Documentation needs Multiplatform Instructions

### ISSUE THREAD

**Issue by brettyjames** [scorelab/Bassa#383]
## Expected Behavior
The instructions to setting up the development environment should have options for Mac, Linux, and Windows.
The documentation should be improved in order to assist users of the main operating systems, not just ambiguous UNIX style commands.

## Current Behavior
There is no sudo command on Windows.
Windows returns an error on use of this command and can do no further.

## Possible Solution
There needs to be a guide for Windows users to setup the development environment.

## Context
The issue does not directly affect me because I'm a MacOS user, I'm just thinking of ways the documentation can be improved. 

## My Environment
* Version used: Current version of this github repository.
* Environment name and version: Python 3.6.3, Node 8.9.3, Pip3
* Operating System and version (desktop or mobile): Windows 10 Desktop (Virtual Machine)
* Link to your project: N/A

**Comment by malithsen** [comment]
Hi @brettyjames 
A windows installation guide is available in the wiki https://github.com/scorelab/Bassa/wiki/Windows-Installation-Guide
