### ISSUE TITLE
Lack of information

### ISSUE THREAD

**Issue by kartiknawani** [scorelab/Bassa#395]
The installation sub menu in Readme.md shouldd contain more information on how to install it.There should be a link to a tutorial where it tutors you how to,what to do while installing and after installing.
For a person new to bassa and python like me , he/she should recieve more information about the program.

**Comment by malithsen** [comment]
Please specify what information the README.md lacks so we can improve it

**Comment by malithsen** [comment]
There are installation guides available in the wiki. Maybe it's better to add a link to README as well
