### ISSUE TITLE
Inconvenience in opening downloaded File. 

### ISSUE THREAD

**Issue by emgaurv** [scorelab/Bassa#398]
## What is the Problem?
I've used Bassa Project about half an hour & everything was working fine but I've seen that whenever I download any File its Summary available in "COMPLETED SECTION " and there is no Button to Open that file unless or until we open UI folder which is in Bassa Project Directory, This is so Inconvenient for
User.

## Solution
For the solution of this problem if we add a "show in folder" button which is shown in the image below. That would be really helpful for the user.

![up](https://user-images.githubusercontent.com/17242746/34642356-8aa6df80-f337-11e7-8f9d-f7513bcdb60c.jpg)

**Comment by tanmayanand44** [comment]
@agentmilindu @malithsen  I will work on this issue.

**Comment by kmehant** [comment]
So We store these downloaded files in a local server and download them to our system whenever required so we have got download button for the completed files. 
So I am closing the issue.
