### ISSUE TITLE
Should have a new look as this one looks old.

### ISSUE THREAD

**Issue by Shashank-Maurya** [scorelab/Bassa#401]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by malithsen** [comment]
Hi @Shashank-Maurya This issue is too broad. Please specify which which part of UI can be improved and your reasons. Please create a new issue by following the issue template
