### ISSUE TITLE
Having problem in cloning the file

### ISSUE THREAD

**Issue by Shashank-Maurya** [scorelab/Bassa#405]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by malithsen** [comment]
Please be more descriptive when filing an issue. What exactly goes wrong?
Follow the issue template
