### ISSUE TITLE
Should have tutorials of using Git for new users.

### ISSUE THREAD

**Issue by Shashank-Maurya** [scorelab/Bassa#406]
## Expected Behavior

It should have tutorials on how git works for new users as when I used Git for the first time, I was also unable to use it.

## Current Behavior

The current screen of Git does not have tutorials to help new users.
## Possible Solution

Should update the version with tutorials for new users

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
First I was unable to use Git but when I looked youtube for the tutorials then I learn't Git.

## Your Environment

* Version used:I used the website of Git
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):Windows 7
* Link to your project:

**Comment by malithsen** [comment]
Out of scope of Bassa
