### ISSUE TITLE
Separate out `aria2` from the Bassa core and finish Dockerizing Bassa

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#407]
- [x] `aria2` should be taken out from Bassa
- [x] `aria2` should be running in a Docker container
- [ ] Optime all the Dockers for Production use
- [x] Wire all the Docker containers with Docker Compose

**Comment by Boot-Error** [comment]
I can take up the issue.

Since the code base uses aria2c via its JSONRPC api, the code can be kept untouched.
Use docker-aria2c and link that running container to api server container, along with a volume added to the aria2c container that stores the downloaded content.

**Comment by agentmilindu** [comment]
Yeah, you can go ahead!

**Comment by Asutosh989** [comment]
@agentmilindu I am interested to solve this issue. Can I take up this issue?

**Comment by kmehant** [comment]
Fixes here: https://github.com/scorelab/Bassa/pull/793
So closing this for now as there existing a similar issue linked with the **PR** 😄
