### ISSUE TITLE
Package Bassa into a installer

### ISSUE THREAD

**Issue by sarang-s** [scorelab/Bassa#410]
## Your documentation can only be understood by developers.

Make a Bassa installer so that non coders or non developers can setup a server easily and use it
The documentation shows that a lot of installation of different packages is necessary for setting up Bassa.
If you could package all the necessary installations into a Installer,  it would enable developers and non developers to use it easily.

**Comment by malithsen** [comment]
This is already in progress as GCI tasks :)
