### ISSUE TITLE
Make CLI tool for Bassa to do managing tasks

### ISSUE THREAD

**Issue by vivonk** [scorelab/Bassa#428]
## Improvement that can be helpful for serving this tool in better way
Right now the Bassa server need to give a command based start like this
```
python3 Main.py
gulp serve
```
where as, to make it a useful tool, improvement should be
```
bassa start | stop | restart # service to handle bassa server
bassa global --config.port=5001 # assigning different port to Bassa
bassa add user="noob" pass="opensourceisatrick"
```
## Expected work that have to done

- Linux/Window/MacOS supported tool
- Improving functionality in different manners (e.g Multi database support)
- Making OS based packages from the current code base in a single repository

**Comment by vivonk** [comment]
@agentmilindu @iammosespaulr Please add more things in this

**Comment by agentmilindu** [comment]
This idea looks good to me! 

@charithccmc @rehrumesh @malithsen @JaDogg

**Comment by agentmilindu** [comment]
I think this Python CLI would be a Bassa API consumer just to make things easy for the Bassa maintainer. But still have to do the deployment as usual. I see no point giving this CLI heavy loads like setting up Bassa. The CLI client would be a lightweight tool that communicates with Bassa server hosted anywhere. 

Setting up Bassa should be automated with scripts or by using package mangers like APT or Snaps. Dockers and Docker-compose, Kuberneties, etc would come in handy for places which they have these kind of container orchestrations already exists.

**Comment by agentmilindu** [comment]
The context of a place which has a lot of servers is a bit different than we deploying Bassa on our local machines. Mos of the cases, they have container orchestration mechanisms like Kubernetes, Docker swarms, Rancher, etc. Or they have VM orchestration mechanisms like  OpenStack, etc. 

Having an APT package is good. But how well we can setup database servers, etc with APT and guarantee the scaling of the app also happens. But if we can provide these, I'm fine with having a APT package, even a Snap. 

What I said was, we can for sure have a client CLI to communicate with the Bassa server and to do stuff. Like adding downloads, users, etc, restarting the server, flushing the queues, terminating all the downloads, etc.

**Comment by vivonk** [comment]
> What I said was, we can for sure have a client CLI to communicate with the Bassa server and to do stuff. Like adding downloads, users, etc, restarting the server, flushing the queues, terminating all the downloads, etc.

Hopefully, SSH will best to get connected and do concerns. And I am working on it for the apt package. I have made some services for the Bassa and trying to add some roles to it. 
About the scaling, we can consider that the servers are more like to the normal servers, say Linux based machines, which are having the ability to do all the work, which the Bassa server do for a normal system. :smile:

**Comment by kmehant** [comment]
I am closing this as a **PR** from @vivonk has been merged solving it 😃 .
