### ISSUE TITLE
Login gives out 500: Internal Server Error

### ISSUE THREAD

**Issue by menuka94** [scorelab/Bassa#431]
Cannot log in using 'rand' and 'pass' after building Bassa. Error message in the console output: `POST http://localhost:5000/api/login 500 (INTERNAL SERVER ERROR)`

## Expected Behavior

Should log in and redirect to the dashboard or display an error message.

## Current Behavior

No visible output or change in the UI. The error is only displayed in the browser console.

## Possible Solution

Provide an error description to the user.

## Steps to Reproduce (for bugs)

1. Clone the repository
2. Build using the steps mentioned in README
3. Run with `gulp serve`
4. Provide username 'rand' and password 'pass' and log in.

## Context

Trying out a fresh build

## Your Environment

* Version used: 
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 6.13.0, Chrome: Version 64.0.3282.140 (64-bit)
* Operating System and version: Ubuntu 16.04 LTS (64-bit)

**Comment by vivonk** [comment]
I think this is same of #430, try to check first before adding a new issue

**Comment by menuka94** [comment]
Apologies for adding a duplicate issue. However, I did search before creating the issue and there was no mention of an explicit Internal Server Error. #351 says 403 Forbidden and #430 says 'If API is not working then an internal server error should be shown on the UI'. There's no 'if' here. This 'is' an Internal Server Error right off the fresh build of a new clone. Hence the new issue.

**Comment by vivonk** [comment]
I think you are getting wrong. #351  is about all APIs, it's maybe the error 300 or 400 or 500. However when you are facing 500 internal server error then it's your configuration fault, not a codebase issue. DIscuss your configurations on chat and let's solve it.

**Comment by menuka94** [comment]
Sure. Thanks.

**Comment by malithsen** [comment]
Hi @menuka94 
1. Is the backend server running?
2. Is DBCon.py configured with your db credentials?

**Comment by menuka94** [comment]
@malithsen The server was running. But I had wrongly ordered the arguments in `MySQLdb.connect()` function. It worked after using `MySQLdb.connect(host="host", user="username", passwd="password", db="Bassa")`. It works now!
Thanks for the tip :)
