### ISSUE TITLE
Bassa does not start anymore

### ISSUE THREAD

**Issue by Asutosh989** [scorelab/Bassa#435]
Attempt to start Bassa fails with a python `ModuleNotFound`  error:

```
(env)  ✘  ~/Code/Bassa/components/core   master ●  python Main.py
Traceback (most recent call last):
  File "Main.py", line 3, in <module>
    from REST import *
ModuleNotFoundError: No module named 'REST'
```

## Expected Behavior
Bassa server should start

## Current Behavior
Fails with `ModuleNotFoundError`

## Possible Solution
Changes issued by https://github.com/scorelab/Bassa/commit/af72fc9e2258a5c129abea5e7bb2c755e22730e8 has not been synced with `Main.py`. Changing the set of imports should do the trick, I guess.

`REST.py` has been split and renamed but, `Main.py` still depends on it.

## Steps to reproduce
1. Setup Bassa dev environment
2. run `python Main.py` inside `components/core`

## Environment
- Ubuntu 17.10
- Python 3.6.4 :: Anaconda, Inc.

**Comment by Asutosh989** [comment]
After a bit of digging, I found that it's not possible by a simple rename.

So the possible solutions here would be either to:
 - Revert commit https://github.com/scorelab/Bassa/commit/af72fc9e2258a5c129abea5e7bb2c755e22730e8
 - Use [Flask Blueprints](http://flask.pocoo.org/docs/0.12/blueprints/#blueprints)

**Comment by agathver** [comment]
Same issue :/

**Comment by saisankargochhayat** [comment]
@malithsen @padamchopra  is Bassa with the latest commit working for you guys?

**Comment by padamchopra** [comment]
No, it isn't working. #429 by @vivonk is aimed at fixing this (he has incorporated Flask Blueprints)
