### ISSUE TITLE
Lack of documentation for the dependancies when installing bassa server

### ISSUE THREAD

**Issue by rmddcr** [scorelab/Bassa#447]
There is no precise environment  dependency-list needed for installing bassa sever in the relevant environments.
Add those dependencies to read me file would be nice.  :)

**Comment by malithsen** [comment]
Hi @rmddcr Dependencies will be installed automatically by the installation scripts. Installation guides for each platform are available in the wiki https://github.com/scorelab/Bassa/wiki
If there's any specific dependency that is omitted in the installation process, please feel free to open another issue following our issue template. I am closing this for now :)
