### ISSUE TITLE
As a User, I should be able to download multiple files at the same time

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/Bassa#457]
User don’t have to put download one after one to download in queue, a concurrect connection for downloads will be there. ( Ex. Google Drive allow multiple zip download at same time)

**Comment by sk9331657** [comment]
@agentmilindu  Can I work on it??

**Comment by agentmilindu** [comment]
@vivonk I think we already completed this, right? Is there anything more to be done?

**Comment by vivonk** [comment]
@agentmilindu @sk9331657 It's done as a sub-issue of https://github.com/scorelab/Bassa/issues/453 
Closing from here
