### ISSUE TITLE
Add import statement for parse_requirements for pip above 10

### ISSUE THREAD

**Issue by phoenixking25** [scorelab/Bassa#481]
Import statement for parse_requirements in setup.py is different from pip <= 9.0.3 

## Expected Behavior

Smooth installation on running `sudo python3 setup.py develop` 

## Current Behavior

On running `sudo python3 setup.py develop` while deploying an error occur `ModuleNotFoundError: No module named 'pip.req'` 

## Possible Solution

`try: # for pip >= 10
    from pip._internal.req import parse_requirements
except ImportError: # for pip <= 9.0.3
    from pip.req import parse_requirements`

## Steps to Reproduce (for bugs)

1. `sudo python3 setup.py develop`

**Comment by vivonk** [comment]
https://github.com/scorelab/Bassa/pull/468
This issue is already resolved. Try to do things with develop branch, not master one.
Thanks for your concern :blush:
