### ISSUE TITLE
Add download input field must return to untouch state after adding any link(UX)

### ISSUE THREAD

**Issue by phoenixking25** [scorelab/Bassa#484]
Add download input field must return to untouch state after adding any link instead of validation error(red) state. 

## Expected Behavior

After adding the download link the input field must set to untouched form state.

## Current Behavior

It goes in validation error state.(RED)
![red](https://user-images.githubusercontent.com/22527880/46249105-235cc200-c441-11e8-8f62-c3d2f3375d0f.gif)

**Comment by aakashbansal** [comment]
I would like to work on this issue!

**Comment by phoenixking25** [comment]
Sure!

**Comment by aakashbansal** [comment]
Hey I have solved the issue. @phoenixking25 @vivonk Please review it! :)

**Comment by aakashbansal** [comment]
#485
