### ISSUE TITLE
Problem with docker build in Travis CI

### ISSUE THREAD

**Issue by vivonk** [scorelab/Bassa#488]
## Current Behavior

Whenever a new PR comes, docker build fails. It's happening from some time like last 6-7 PR.

### Error  -  
> The command "docker build --build-arg VCS_REF=`git rev-parse --short HEAD`   --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` -t scoreucsc/bassa  ." exited with 1.

## Possible Solution

I am not sure where is the problem but I guess the problem is on our codebase itself.
## Steps to Reproduce (for bugs)

1. Run the docker build on local
2. Check for different branches
3. Rewrite Travis configurations for this particular problem

**Comment by vivonk** [comment]
This issue was opened wrongly. Sorry for that

**Comment by VibhorCodecianGupta** [comment]
@vivonk is this not an issue anymore?

**Comment by vivonk** [comment]
No

**Comment by VibhorCodecianGupta** [comment]
What seemed to be the problem exactly? Why were the builds failing?
