### ISSUE TITLE
Temporary duplicated file links when adding or removing downloads

### ISSUE THREAD

**Issue by aakashbansal** [scorelab/Bassa#489]
Whenever the user adds new download link or deletes the existing one, the list gets updated. But while the list is being updated, there is some duplicacy of the file links.

Please refer the screenshot :

![temp-repeated-files](https://user-images.githubusercontent.com/16841267/46311088-c26af080-c5de-11e8-84ba-f4b59688408b.gif)

**Comment by aakashbansal** [comment]
I would like to tackle this issue!

**Comment by vivonk** [comment]
Nice @aakashbansal , go for it :+1:
