### ISSUE TITLE
User name should be displayed on the top (UX)

### ISSUE THREAD

**Issue by aakashbansal** [scorelab/Bassa#490]
As of now, the user name does not get displayed anywhere on the screen. The only way to know the username would be to click the hamburger icon that show log out button. Displaying the user name over the top would improve the UX.

Current scenario :
![user name](https://user-images.githubusercontent.com/16841267/46311519-19bd9080-c5e0-11e8-83e5-abe8926f1e15.png)

**Comment by VibhorCodecianGupta** [comment]
@vivonk please review #492 :)
