### ISSUE TITLE
Add forgot password feature.

### ISSUE THREAD

**Issue by phoenixking25** [scorelab/Bassa#495]
# Add forgot password feature.

## Expected Behavior
 - There should be a button on ui which send password reset email to the respective user which redirects to password reset form

## Current Behavior
 - There's no such feature.

**Comment by VibhorCodecianGupta** [comment]
Nice catch! You working on this?

**Comment by phoenixking25** [comment]
nope! you can do this.

**Comment by VibhorCodecianGupta** [comment]
Great! I'm working on this then

**Comment by phoenixking25** [comment]
Sure.

**Comment by phoenixking25** [comment]
@VibhorCodecianGupta if you haven't started this issue i want to put this task in my GCI task.

**Comment by phoenixking25** [comment]
@vivonk add GCI label on it. i want to enlist this in my gci tasks.

**Comment by phoenixking25** [comment]
@vivonk check now.

**Comment by vivonk** [comment]
@agentmilindu please see whether it's something that GCI participants will able to do in specific time

**Comment by agentmilindu** [comment]
@vivonk @phoenixking25 I think we have to divide this issue into several tasks if we are adding this to GCI.

1. Add a hyperlink "Forgot password" on the login screen, Clicking the link opens a Forgot Password form to ask the email.
1. When the form is submitted, send an email to the user with Password Resetting Link.
1. Create a Password Resetting page, this is the page where the users land when the Password Resetting Link is clicked. Password Resetting token should be taken from the link and stored in a hidden input field along with a CSRF token. 
1. When the Password Resetting form is submitted, validate the tokens and reset the passwords to the new password.
1. Send the mail to the user notifying that his/her password has got successfully reset.

Some tasks are hard and some are medium hard, but we have to publish the task in doable order. For example, 4th one cannpt be done untill 3rd is done. We have to mindull on these too. We can create the tasks and publish in order.

**Comment by phoenixking25** [comment]
Ok will publish this in that order.

**Comment by ganeshpatro321** [comment]
Hey @vivonk Is this issue resolved, if not can I pick this issue?

**Comment by Bhavyagautam08** [comment]
May I work on this ??
