### ISSUE TITLE
Unnecessary empty fields in the UI

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [scorelab/Bassa#502]
## Current Behavior
The project currently has fields which are displayed with their respective headings even when there is no corresponding data to be displayed. Screenshots follow: 

![screen shot 2018-10-04 at 12 52 51 am](https://user-images.githubusercontent.com/29275810/46434303-e9592c00-c770-11e8-982b-d289c3425b0b.png)

![screen shot 2018-10-04 at 12 53 12 am](https://user-images.githubusercontent.com/29275810/46434305-e9f1c280-c770-11e8-8fa5-cad0904857bd.png)

![screen shot 2018-10-04 at 12 53 33 am](https://user-images.githubusercontent.com/29275810/46434306-e9f1c280-c770-11e8-96ad-4135ae513a00.png)

Signup requests, Table headings in the completed tab and 'On going downloads' look redundant when there is no data to display.

## Expected Behavior
The redundant headings/sections should disappear if there is no data to display in them

## Possible Solution
The simple solution to be employed is putting in an `ng-if` condition, checking whether there is data to display or not. If there isn't, the particular section is not rendered.

**Comment by VibhorCodecianGupta** [comment]
This is meant for GCI task

**Comment by vivonk** [comment]
Nice idea. You can add this to the GCI tasks.

**Comment by harsha-iiiv** [comment]
Can i work on this issue?
