### ISSUE TITLE
Conserving memory while making API calls from the frontend

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [scorelab/Bassa#503]
## Current Behavior
While making an API call to the backend which fetches all the downloads (queued or downloaded), the code uses `filter` function to filter the queued downloads and then maps them. This process takes up a lot of extra space as both `filter` and `map` functions create new arrays, hence allocating extra memory twice for the same task. Since this API is being called every time a user adds a link to be downloaded, it becomes pretty memory inefficient.
Code snippet: https://github.com/scorelab/Bassa/blob/1294190d79cc00f98e0579455564634ac858b015/ui/src/app/dashboard/controllers/DashCtrl.js#L63

## Expected Behavior
Minimal and judicious use of memory is the goal.

## Possible Solution
Using the `reduce` function on the response array, instead of `filter` and `map`. The reduce function, written accordingly, can easily carry out the task of filter and map in the same iteration, and it returns the very same array without creating new ones, and hence saves memory.

Resources:
https://codeburst.io/reduce-filter-and-map-without-reduce-filter-and-map-787c21671c95
https://medium.freecodecamp.org/reduce-f47a7da511a9
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

**Comment by VibhorCodecianGupta** [comment]
@vivonk again, the change is minimal, intended as a GCI task

**Comment by VibhorCodecianGupta** [comment]
@vivonk for GCI

**Comment by harsha-iiiv** [comment]
Can i work on this issue!?

**Comment by VibhorCodecianGupta** [comment]
@vivonk @agentmilindu done in #683
