### ISSUE TITLE
Add GitHub link of Bassa on the login page 

### ISSUE THREAD

**Issue by swatisingh45** [scorelab/Bassa#511]
In order to increase visibility add GitHub link to Bassa project on the login page. 

## Expected Behavior

- Simply should contain the GitHub logo at the center to the bottom of the page so that when clicked should direct to the GitHub link of the project. 

## Current Behavior

- Not in implementation.

## ToDo

- Create a Pull request making your changes.

## Submission Requirements:

- Link to your created PR

**Comment by swatisingh45** [comment]
@vivonk Please review this, it's for GCI.

**Comment by harsha-iiiv** [comment]
Can i work on this issue?

**Comment by VibhorCodecianGupta** [comment]
@harsha-iiiv this is enlisted as a GCI task. I'd encourage you to pick up an issue that someone isn't already working on, or feel free to open new ones!

**Comment by harsha-iiiv** [comment]
@VibhorCodecianGupta  thank you.

**Comment by jerrytoms** [comment]
Can I work on this issue?
