### ISSUE TITLE
Add a bash script for setup in OSX environment

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [scorelab/Bassa#515]
## Expected Behavior

There should be a bash script containing all the installation commands for OSX, so as to make installation a one-command process.

## Current Behavior

There is no setup file present for OSX, although steps are listed down in the wiki.

## Possible Solution

Create a `setup_osx.sh` similar to `setup.sh` in the root directory. All the commands that are required are already present in the wiki.

## Follow-up
Update the README.md accordingly.

**Comment by VibhorCodecianGupta** [comment]
@vivonk intended as a GCI task

**Comment by swatisingh45** [comment]
@VibhorCodecianGupta  Please do not mention this here, just add this on your dashboard, admins will review them further later.

**Comment by VibhorCodecianGupta** [comment]
@agentmilindu @vivonk done in #673
