### ISSUE TITLE
Should add gitattributes file to this project

### ISSUE THREAD

**Issue by ChaminW** [scorelab/Bassa#520]
## Expected Behavior
Make pull request from all contributors without introducing any conflicts in encoding.

## Current Behavior
Without a normalized line endings, pull request from varies contributors may introduce conflicts due to generalized encoding types in different IDEs and operating systems.

## Possible Solution
Add a gitattributes file with proper attributes

**Comment by agentmilindu** [comment]
@ChaminW Agree, please go ahead for a PR

**Comment by agentmilindu** [comment]
@ChaminW Thanks for the PR!
