### ISSUE TITLE
Improvement Proposal

### ISSUE THREAD

**Issue by bauripalash** [scorelab/Bassa#609]
As all can see the master branch is not working at all and not maintained anymore. 

**I think it would be better to pull all the changes in develop branch to the master branch whenever a stable version is released.**

> As for now if we try to run the program from master branch it doesn't work very well , but develop branch seems to work fine.

And I would recommend to use a proper semantic version numbering and make use of the GitHub release system.

**Comment by VibhorCodecianGupta** [comment]
@bauripalash that already happens, all the changes are to be pushed to develop only

**Comment by bauripalash** [comment]
Then why not make 'develop' the default branch

**Comment by VibhorCodecianGupta** [comment]
The master branch is for the releases as you can see. So the develop branch has all the CI passing, and every working piece of code is merged there. The maintainers will merge all that chunk into master and release it as version 1.0.0 as far as I think. Making develop default wouldn't really achieve anything

**Comment by bauripalash** [comment]
Got it! But when they gonna release 1.0.0?

**Comment by kmehant** [comment]
@VibhorCodecianGupta has given a proper explanation. We have got senior developers here who would take care of proper releases. Closing this issue.
