### ISSUE TITLE
Containerize Bassa using Docker

### ISSUE THREAD

**Issue by rehrumesh** [scorelab/Bassa#63]

**Comment by SonaArora** [comment]
@rehrumesh Hi, i want to work on this issue. Can you please tell me more about this.

**Comment by rehrumesh** [comment]
@SonaArora primary intention of this task to make Bassa a containerized application using Docker. As the initial step you can create a dockerfile in the repo and make a docker image out of it. In later we can create a sample docker-compose file so it will be a multicontainer application where front-end, backend and database resides in 3 different containers.

**Comment by vivonk** [comment]
@rehrumesh @agentmilindu can you please tell like how the existing docker build is working or is working or not?

**Comment by kmehant** [comment]
This featured has been completed and merged into develop. Closing this issue for now 😄
