### ISSUE TITLE
gh-page for Bassa

### ISSUE THREAD

**Issue by harsha-iiiv** [scorelab/Bassa#671]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by prashant0598** [comment]
@harsha-iiiv Pls make the issue more informative.

**Comment by vivonk** [comment]
@malithsen I guess we already have web hosting and that is not a project specific. So should we go for this or a single website + readme in every repo is enough?

**Comment by kmehant** [comment]
I think we have got enough **wikis** and **documentation** to work on **Bassa**. So closing this for now. 

@harsha-iiiv if you would like to implement a static website for Bassa then open this issue and send a **PR** for the same referencing it. Or if you want to have a separate repo for the static website so please discuss it in the **gitter** channel.
