### ISSUE TITLE
Implementation of unit tests

### ISSUE THREAD

**Issue by rajikaimal** [scorelab/Bassa#68]
Proposed methodology for unit testing.
- Unit test implementation with [Jasmine framework](https://jasmine.github.io/).

@rehrumesh

**Comment by rehrumesh** [comment]
Hi @rajikaimal, initial steps and few basic test cases have been writtn by @malithsen. Please have a look at it of you are interested in contributing.

**Comment by rajikaimal** [comment]
Great !
