### ISSUE TITLE
Broken dashboard

### ISSUE THREAD

**Issue by malithsen** [scorelab/Bassa#691]
UI no longer show queued or completed downloads

## Expected Behavior
Show queued downloads of the logged in use
Show a list of completed downloads

## Current Behavior

Empty queue and completed list. On inspection it was observed that the files are getting downloaded as expected however they don't show up anywhere on the UI

This shows up on console:
![bassaerr](https://user-images.githubusercontent.com/6216000/51804619-7167c200-2289-11e9-83bc-ad6f34fdf8c2.png)

## Steps to Reproduce (for bugs)

1. Log in
2. Add download link
3. Start downloads as admin

## Your Environment

* Version used: Latest dev branch
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 69, Node v8.9.3
* Operating System and version (desktop or mobile): Arch

**Comment by VibhorCodecianGupta** [comment]
Looking into it ASAP

**Comment by malithsen** [comment]
@VibhorCodecianGupta 
It looks like we're assigning the result from api to $scope.downloads here
https://github.com/scorelab/Bassa/blob/develop/ui/src/app/completed/controllers/TableCtrl.js#L36

but in the view we check for something else
https://github.com/scorelab/Bassa/blob/develop/ui/src/app/views/table.html#L1

**Comment by malithsen** [comment]
Hi @VibhorCodecianGupta do you have any updates on this?

**Comment by kmehant** [comment]
@malithsen I think it needs a small angular fix which is being done in this **PR** https://github.com/scorelab/Bassa/pull/756. Please look into it.

**Comment by kmehant** [comment]
Fixes in #794 So closing this for now.
