### ISSUE TITLE
Windows Installation Error for higher versions of PIP 

### ISSUE THREAD

**Issue by RavinduSachintha** [scorelab/Bassa#695]
There have use **pip.req** internal API in the setup.py file and the way it has used, have been changed after the **pip version 10**.
[https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html](https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html)

## Expected Behavior
Successfully get the required dependencies using requirements.txt without an error.

## Current Behavior
Gives an error such that,
```
File "setup.py", line 6, in <module>
    from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req'
```
## Your Environment
* Environment name and version (e.g. Chrome 39, node.js 5.4): pip 19.0.2 / Python 3.6.8
* Operating System: Windows 10

**Comment by xlight05** [comment]
This is not a windows specific issue.  Try using 'develop' branch. A fix is available there :)

**Comment by kmehant** [comment]
I don't think there is any problem with pip's version. as @xlight05 said please work on the updated `develop` branch and I am sure everything should be fine.  Please look at the wikis too. Closing this for now. If you further have any specific issue please feel free to open an issue as well post it in our gitter channel.
