### ISSUE TITLE
Error on running gulp serve

### ISSUE THREAD

**Issue by kartikpandey2** [scorelab/Bassa#696]
On running `gulp serve` to start front end server it gives the error 
```Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime```

## Expected Behavior

It should run the front end server

## Current Behavior

It throws an error

## Possible Solution

On some research I found we are using very old packages which don't support nodejs recent versions.
For eg:
We are using ["node-sass": "^4.5.0"](https://github.com/scorelab/Bassa/blob/master/ui/package.json#L101)  which only supports [Node.js versions 0.10, 0.12, 1, 2, 3, 4, 5, 6 and 7](https://github.com/sass/node-sass/tree/v4.5.0) 

* We should update old packages so that they can support recent node version (preferred).
*  We can specify node version required in readme to run project  on windows machine.

## Steps to Reproduce (for bugs)

1. Navigate to ui directory
2. Run npm install
3. Run gulp serve

## Your Environment

* Environment name and version:
`node.js -v: v8.14.0` 
* Operating System and version:
Windows 10

**Comment by ganeshpatro321** [comment]
@vivonk 
@kartikpandey2 There is a similar issue with ubuntu 18.04 too.
![screenshot from 2019-03-02 01-09-06](https://user-images.githubusercontent.com/30416891/53662118-2118c100-3c88-11e9-849b-81dae66925a0.png)

**Comment by kartikpandey2** [comment]
@ganeshpatro321  you need to downgrade to node 6 to make it work.

**Comment by ganeshpatro321** [comment]
I ran it using node 6.10.1, still facing the same problem?

**Comment by ganeshpatro321** [comment]
![screenshot from 2019-03-02 18-00-35](https://user-images.githubusercontent.com/30416891/53681926-481dd400-3d16-11e9-954f-deec06c47fbd.png)

I am using downgraded node version, still not able to setup things. Help would be greatly appreciated. Thank You.
@vivonk

**Comment by demon-36** [comment]
@ganeshpatro321 I had same problem while installing Bassa. This problem is with ubuntu 18.10 version,
I was having installed 18.10 Cosmic version which was not stable and I think same version you are using.
 Install stable version of 18.04 and then again install Bassa step by step, that worked for me.
Good luck !

**Comment by ganeshpatro321** [comment]
Hey @demon-36 , I am using ubuntu 18.04, but not getting why this error is popping up.

**Comment by kmehant** [comment]
Closed it for now! you can find this in troubleshooting issue which is pinned 😃
