### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by kartikpandey2** [scorelab/Bassa#699]
Login to Bassa with cred `rand`, `pass`throws `Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)` but no error is logged on the server console.

![screenshot 145](https://user-images.githubusercontent.com/20434963/52916700-d5b9f680-3308-11e9-8467-5c2a39f1100b.png)

## Expected Behavior

Login should work

## Current Behavior

server returns 504(internal server error)

## Steps to Reproduce (for bugs)

1. Try to login with username `rand` and password `pass`

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4): nodejs 6.12.0
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by malithsen** [comment]
Are there any errors in backend logs? A common reason for this error is a problem with database connection. Please verify if the database credentials are properly set

**Comment by kartikpandey2** [comment]
@malithsen It is not a connection issue. I finally found what makes server to throw 504 error. I am on windows platform so I followed [this(mentioned on Windows Installation Guide)](https://www.youtube.com/watch?v=QAQaThaUOgE&feature=youtu.be) to setup Bassa locally. In this tutorial he changed `import MySQLdb` to `import pymysql
pymysql.install_as_MySQLdb()` in [DBCon.py](https://github.com/scorelab/Bassa/blob/master/components/core/DBCon.py#L1) file. Thus making [MySQLdb](https://github.com/scorelab/Bassa/blob/master/components/core/UserManager.py#L53) `undefined` throughout project.

**Comment by demon-36** [comment]
@kartikpandey2 for Linux OS, while setting up **_DBCon.py file_** just edit the variables as 
_db=MySQLdb.connect("localhost", "root", "pass", "Bassa")

**Comment by kartikpandey2** [comment]
@demon-36  I am on Windows

**Comment by xlight05** [comment]
@kartikpandey2 
You should change DBCon.py on windows too(If you don't have env variables).
https://github.com/scorelab/Bassa/wiki/Windows-Installation-Guide

**Comment by kmehant** [comment]
Make sure 
* Mysql:5.7 is running 
* Bassa API server is running 
* both servers are connected and able to exchange requests. 
I think this should fix things. Closing this issue for now but it will be part of the **troubleshooting list**
