### ISSUE TITLE
Enable Console Logging

### ISSUE THREAD

**Issue by xlight05** [scorelab/Bassa#708]
## Context
I've noticed so many people (including me) failing to set up the database credentials in the first try.
In the current version of Bassa if you did not set up the database correctly, you won't get any errors until you try to login with the UI.
This can be an issue of documentation however since we have 'Server initialized for gevent.' message after launching Main.py the user expects the error logs to be there. 

IMO, Console logging will solve this problem and its fairly easy to implement. Console logging is a general best practice and its adapted in most open source projects. This will make life even more easier when we are deploying Bassa in platforms like docker , kuberentes. (kubectl logs)

**Comment by Shehanka** [comment]
Still I couldn't run app locally. I really like to contribute this project in GSoC but thing is difficult to setup this project. When I run Main.py I got an error again.

**Comment by xlight05** [comment]
@Shehanka This issue is not related the issue you are facing, 
Send me a msg in gitter with the error you are getting :)

**Comment by xlight05** [comment]
Resolved with #709
