### ISSUE TITLE
Implement a single dependency setup shell script for linux distros and MacOS

### ISSUE THREAD

**Issue by kmehant** [scorelab/Bassa#714]
## Expected Behavior

Implement a single setup shell script for dependency installation across linux distros and MacOS
## Current Behavior

There is a setup shell script only for Linux Ubuntu (apt/apt-get based) OS.
There is no shell script for installation of dependencies across variuos other linux distros and MacOS.
## Possible Solution

A single dedicated setup shell script which can install dependencies automatically recognising most of the linux distros or MacOS.

**Comment by VibhorCodecianGupta** [comment]
#673 does this partially. Other Linux distros could be added over there itself I guess, since I originally intended it to be inclusive of other OS as well?

**Comment by kmehant** [comment]
Hi Vibhor, 
I wrote this MacOS setup on wiki last year(https://github.com/scorelab/Bassa/wiki/MacOS-Installation-Guide). So your issue was specifying mainly around having a specific setup script only for MacOS. So I created a common script for all the Linux distros and MacOS included. But if you feel this issue is a mistake or want me to remove MacOS installation steps please let me know.
@vivonk @agentmilindu
