### ISSUE TITLE
[UI/UX Improvement] Display logout button next to user name

### ISSUE THREAD

**Issue by arc9693** [scorelab/Bassa#717]
## Expected Behavior
Logout button should appear next to the username so that the user can logout at one click.

## Current Behavior
Currently, there is a drop down menu next to username that contains only one button to logout so the user needs to click twice in order to logout which is not a good user experience.

![Screenshot from 2019-03-25 21-41-13](https://user-images.githubusercontent.com/36061892/54936129-cfdab500-4f47-11e9-9dd4-ddc1a5c48a69.png)

**Comment by avsingh999** [comment]
we can add the logout icon and add tooltip there when hovering on logout icon then show log out.
what do you think @arc9693

**Comment by arc9693** [comment]
@avsingh999 Yes. That would be better.
