### ISSUE TITLE
[Unit tests] Using ChromeDriver instead of PhantomJS

### ISSUE THREAD

**Issue by rajikaimal** [scorelab/Bassa#72]
`ChromeDriver` can be used instead of the `PhantomJS` driver which is currently used in the project for unit tests. As `Phantom2` is being developed heavily breaking changes can be introduced. In fact when configuring the project for unit tests I got several breaking changes due to Phantom2 releases and it's plugin changes. Therefore I propose to use `ChromeDriver` instead of `PhantomJS` since Chrome is a stable project and can be used for heavy unit tests and `e2e` tests can be handled smoothly with Chrome.

**Comment by malithsen** [comment]
@rajikaimal This makes sense. I too had recurring problems with phantom in last few months. Feel free to issue a PR if you have time.

**Comment by rajikaimal** [comment]
@malithsen sure, I'll submit a PR for this issue.

**Comment by rajikaimal** [comment]
#73 solves this issue.
