### ISSUE TITLE
add linux, mac installtion guide link in Readme.md

### ISSUE THREAD

**Issue by avsingh999** [scorelab/Bassa#720]
there is no link  to the user can go Linux and mac installation guide
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by avsingh999** [comment]
@vivonk If it's valid I will send pr soon.
thanks : )

**Comment by kmehant** [comment]
Please look at this! 
https://github.com/scorelab/Bassa/pull/725#issuecomment-498637043
