### ISSUE TITLE
add file name in gitignore

### ISSUE THREAD

**Issue by avsingh999** [scorelab/Bassa#727]
I think we need to add this file `components/core/DBCon.py` in .gitignore because no need to commit this file this is in local setup.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by avsingh999** [comment]
@vivonk @kmehant what do you think about please review about this?
thanks : )

**Comment by kmehant** [comment]
That makes sense but might not be a good solution. Presently we are using environment variables to set the credentials so that no one needs to statically put the values in the connector method. We might go further implementing .env files to make it better. so closing this issue for now.
