### ISSUE TITLE
improve login system in Bassa

### ISSUE THREAD

**Issue by avsingh999** [scorelab/Bassa#728]
when successfully login in bassa and render to dashboard page but if we open again login link http://localhost:3000/#!/login (when user is always logeed in ) then it's again go to login page.
![scor9](https://user-images.githubusercontent.com/25536022/55088139-3a6b2c80-50d1-11e9-82dc-26b39e329b9b.gif)

## Expected Behavior
if user already login then go to Dashboard page

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by avsingh999** [comment]
@vivonk @kmehant @agentmilindu please review me about this issue.it's valid or not.
thanks : )

**Comment by kmehant** [comment]
That's a valid issue. We have a similar issue posted earlier so I am closing this, for now, referencing to the [other one.](https://github.com/scorelab/Bassa/issues/122)
