### ISSUE TITLE
Add Bassa logo in signup page

### ISSUE THREAD

**Issue by avsingh999** [scorelab/Bassa#729]
in login page here is Bassa logo So we can add a logo in also Bassa Sign up page
![scor10](https://user-images.githubusercontent.com/25536022/55106201-5b914480-50f4-11e9-950f-89167847c218.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by kmehant** [comment]
Seems like it is implemented! so closing this
