### ISSUE TITLE
Downloading of files is not starting

### ISSUE THREAD

**Issue by demon-36** [scorelab/Bassa#730]
Downloading of files is not starting after hitting Start button in Admin section.

## Expected Behavior

Added downloads should be downloaded after hitting Start button.

## Current Behavior

After adding a link of file, when we click start button in Admin Section nothing happens.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by demon-36** [comment]
@vivonk please go through this :)

**Comment by avsingh999** [comment]
Hi, @demon-36 in develop branch it's working but not showing data which files are downloading (request).
thank you : )

**Comment by avsingh999** [comment]
@demon-36  and master branch working fine. please explain to me more if I am on wrong track.

**Comment by demon-36** [comment]
@avsingh999 if this is true then I don't know what's wrong with my machine, I need to find out the issue.

**Comment by avsingh999** [comment]
please post a gif where we can see where is the problem.

**Comment by demon-36** [comment]
![download](https://user-images.githubusercontent.com/31997208/55143564-05a8b500-5165-11e9-8ea1-efc2638acf9d.gif)
here you can see what problem i'm facing.
P.S. : quality is not that much good.

**Comment by kmehant** [comment]
Seems like 
* you are testing it on some other branch other than `develop` branch. As far as I concern, we have a **download** button for the completed files which does not seem to be there in your case.
* You might have not started Aria2c server or have some problem in receiving download requests.  
* or your local current branch might not be in sync with **upstream**
Check these points and you should be able to fix it. So closing this now.

**Comment by vivonk** [comment]
@demon-36 if you still having same issue, please send this error on Gitter channel with System details :)

**Comment by demon-36** [comment]
@vivonk @kmehant  that was due to not syncing local repo with develop repo, currently this is working fine.
