### ISSUE TITLE
adding dark theme feature in Bassa

### ISSUE THREAD

**Issue by singhrohan62** [scorelab/Bassa#733]
I have experienced this problem and I think that adding this feature would make the app more cool. For people who work late at night, the light background might give strain in the eyes hence it would distract from doing their work. Dark theme can provide relief to their eyes.

## Expected Behavior
Right now, I will be adding this option only on Login page just for good first issue and later we can provide this feature everywhere. I think to add a button (right now) to toggle between dark and light mode.

## Current Behavior
The login page is having a light colour background right now.

## Possible Solution
Add a button on top-right corner to toggle between dark and light mode.

## Your Environment
* Version used:1.3.0
* Environment name and version (e.g. Chrome 39, node.js 5.4):nodejs: 10.12, Firefox: 
* Operating System and version (desktop or mobile):Windows

**Comment by demon-36** [comment]
@singhrohan62 instead of adding this button on login screen, it will look great on main screen after getting logged in. Isn't it ?

**Comment by singhrohan62** [comment]
Hi @demon-36, why not on both pages? If you would have read above I have clearly mentioned that I would like to add it in main screen also. Right now, as a good first issue, I am trying to add this feature only on login screen. Won't it make app more cool 😀 ?
