### ISSUE TITLE
change downloads folder

### ISSUE THREAD

**Issue by avsingh999** [scorelab/Bassa#735]
when admin download the files but it's store the files `/Bassa/components/core`.So it would be better if all downloads files will be in a separate folder.
## Expected Behavior
shift downloads files in a separate folder

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by avsingh999** [comment]
@vivonk please review me.
thanks : )

**Comment by kmehant** [comment]
Will be fixed in #793
