### ISSUE TITLE
Grid view button is not functioning 

### ISSUE THREAD

**Issue by demon-36** [scorelab/Bassa#760]
## Expected Behavior

When grid view button is clicked then downloaded files should be shown in Grid.

## Current Behavior

When we click Grid view button then nothing happens along with that table of downloaded files also disappears.

## Possible Solution

fixing working of grid view button in codebase

**Comment by demon-36** [comment]
@vivonk  @agentmilindu  should I go forward to fix this ?

**Comment by hv7214** [comment]
@kmehant anyone on this ? If no, can i take it up ?
