### ISSUE TITLE
image not found in Readme

### ISSUE THREAD

**Issue by avsingh999** [scorelab/Bassa#763]
this link is not working in Readme https://opencollective.com/Bassa/contributors.svg?width=890&button=false
![scor24](https://user-images.githubusercontent.com/25536022/56865796-a18d4100-69ef-11e9-9168-4d152820c74f.png)

## Current Behavior
image not found in this link
https://opencollective.com/Bassa/contributors.svg?width=890&button=false

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by avsingh999** [comment]
@agentmilindu @vivonk Please review about this, because I don't know which image should be shown by that link and what would be the solution of this problem.
thank you : )

**Comment by kmehant** [comment]
@avsingh999 Thanks for the issue, seems like it is fixed now on `develop` branch already, so closing this.
