### ISSUE TITLE
Make Bassa ready for Kubernetes deployments

### ISSUE THREAD

**Issue by kmehant** [scorelab/Bassa#769]
**Is your feature request related to a problem? Please describe.**
Write now Bassa has been completely containerized using Docker and the docker-compose tool has been integrated for easy local deployments. Now we can go step further by deploying Bassa to a Kubernetes cluster for better orchestration and cloud deployments.

**Describe the solution you'd like**
I would like to divide the manifests according to the decided architecture for Kubernetes deployments.

**Comment by hv7214** [comment]
@kmehant are you still assigned on this ?

**Comment by kmehant** [comment]
Please look through the referenced pull requests and most of the work is done which might lead to duplication of work. Anyways you can look through #828.

**Comment by hv7214** [comment]
@kmehant i see, is there any minor work left ?

**Comment by kmehant** [comment]
Fixed :)
