### ISSUE TITLE
Unable to build Docker Image from Dockefile of API server 

### ISSUE THREAD

**Issue by demon-36** [scorelab/Bassa#786]
**Is your feature request related to a problem? Please describe.**
Currently Dockerfile for API sever fails to build Docker Image, so Dockerfile requires enhancement.

**Describe the solution you'd like**
1. Use `ubuntu minimal` as base image for built image optimization
2. adding commands for required package installation which are missing from base image like          `pip`, `python-setuptools`
3. adding required commands for successful installation of `pylint`  
4. Updating `setup.sh` file for core as it aborts the installation of libmysqlclient

**Comment by kmehant** [comment]
It is fixed at #776, so closing it for now :)
