### ISSUE TITLE
Add components Admin and Login to the React application

### ISSUE THREAD

**Issue by singhrohan62** [scorelab/Bassa#795]
**Is your feature request related to a problem? Please describe.**
After creating components `Dashboard`, `Queued` and `Completed`, it's time to create the remaining components and add test how the component would behave on user interaction and what will be rendered in front of the user.

**Describe the solution you'd like**
This time, I would like to follow TDD (Test Driven Development) approach. So, according to the design(mockup) of the components, tests will be created for the component in order to FAIL them first. Later we will add features in the component so as to make the tests PASS.

**Comment by singhrohan62** [comment]
@vivonk  and @agentmilindu  what do you think of TDD approach? Kindly provide your suggestions!

**Comment by vivonk** [comment]
@singhrohan62 I guess TDD would be good approach for writing and designing things from scratch. At the end, it will help us in going to exact path which we decide before. 
I am with TDD Process :+1:

**Comment by singhrohan62** [comment]
Fixed in PR [788](https://github.com/scorelab/Bassa/pull/788)

**Comment by agentmilindu** [comment]
@singhrohan62 I agree, let's follow TDD
