### ISSUE TITLE
Generating empty compressed files 

### ISSUE THREAD

**Issue by kmehant** [scorelab/Bassa#804]
**Describe the bug**
When I try to get the downloaded files I get empty compressed files.

**To Reproduce**
1. Select the files on the dashboard to be downloaded 
2. Click and get the sharable link or simple download
3. Anyway, a compressed file is issued which is empty

**Expected behavior**
Compress folder should have got all the selected files instead of being empty.

**Comment by vivonk** [comment]
Got the problem.
https://github.com/scorelab/Bassa/blob/develop/components/core/file_sender/compression_handler.py#L17
Here we are creating a zip file even if there is no file to zip. It should be like this
```
if len(file_list) == 0 : #nothing to zip
    return 
zip_path = get_zip_path(file_name)

zip_file = zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED)
set_compression_progress(comp_id=file_name, status=status, completed_time=timestamp)
for file in file_list:
	if os.path.exists(file):
		zip_file.write(file, basename(file))
zip_file.close()
```

**Comment by vivonk** [comment]
But the actual problem which is causing this is hidden I guess.
@kmehant can you debug that when you hit a download request where it's getting wrong. I guess to compression handler, no file is getting available.
One thing that is possible is that the time you are trying to download a file,  file might not actually ready. Which means aria2c haven't still downloaded files so they are not available at the paths

**Comment by kmehant** [comment]
@vivonk  sure I will try to draft the compression feature flow and issue related to it.
I will take up this issue!

**Comment by kmehant** [comment]
> Got the problem.
> https://github.com/scorelab/Bassa/blob/develop/components/core/file_sender/compression_handler.py#L17
> Here we are creating a zip file even if there is no file to zip. It should be like this
> 
> ```
> if len(file_list) == 0 : #nothing to zip
>     return 
> zip_path = get_zip_path(file_name)
> 
> zip_file = zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED)
> set_compression_progress(comp_id=file_name, status=status, completed_time=timestamp)
> for file in file_list:
> 	if os.path.exists(file):
> 		zip_file.write(file, basename(file))
> zip_file.close()
> ```

@vivonk That's a needed fix! But seems like there is more to be hunted down to get this feature working!

**Comment by vivonk** [comment]
Ok, can you add this fix in one of your PRs?

**Comment by carpecodeum** [comment]
@kmehant i dont see any PRs for this issue is this issue still open?

**Comment by kmehant** [comment]
Fixed :)
