### ISSUE TITLE
Build React UI for sharing selected files in completed downloads.

### ISSUE THREAD

**Issue by singhrohan62** [scorelab/Bassa#805]
**Is your feature request related to a problem? Please describe.**
The issue is regarding adding a feature of sharing compressed downloaded files as suggested by @kmehant. I am creating an issue as a feature request in the Bassa React application and be listing as a part of my task in the GSoC 2019 project. 

**Describe the solution you'd like**
The completed list component will be displaying list of completed downloads along with the "share" disabled button.
For each file in completed list, a checkbox will be provided and on selecting one or more files, the share button will be enabled and we will be passing suitable function for sharing the files.

**Comment by kmehant** [comment]
@singhrohan62 thanks for taking up the concern.
We have already got API code and endpoints defined for that file sharing feature. API generates a shareable link to download the selected files in the compressed format. We have even got UI in angular for this feature. Hope this helps you in moving further and building it in React 😃
