### ISSUE TITLE
[Feature] A Web Server Gateway Interface for Bassa API server in production

### ISSUE THREAD

**Issue by kmehant** [scorelab/Bassa#811]
**Is your feature request related to a problem? Please describe.**
When we want to use the Bassa API server to serve a large number of clients, it's better to use a WSGI like Gunicorn to serve the application over a worker.

**Describe the solution you'd like**
Integrate a WSGI for Bassa API server for production use. Gunicorn with gevent is preferred to normal flask-socketio server.

**Comment by vivonk** [comment]
@kmehant Gunicorn with gevent is a good option but we can consider `nginx + docker container` on k8s as a good deployment strategy. it's a good point to have discussion on :)

**Comment by JaDogg** [comment]
Gunicorn + Nginx = ❤

**Comment by kmehant** [comment]
> @kmehant Gunicorn with gevent is a good option but we can consider `nginx + docker container` on k8s as a good deployment strategy. it's a good point to have a discussion on :)

@vivonk 
I have made a [**PR**](https://github.com/scorelab/Bassa/pull/813) to use Gunicorn with gevent rather simply a flask-socketio server. 

As @JaDogg bro suggested to use **Nginx** with **Gunicorn** which is a great idea to have for our API server, shall I add Nginx to that [**PR**](https://github.com/scorelab/Bassa/pull/813) as a load balancer transferring the load to multiple workers. 

@vivonk Coming to the nginx with docker container, I have some doubts regarding this. 
Shall we have gunicorn with a single gevent worker? 
As you have mentioned are we going to have multiple docker API containers listening to different ports and a single Nginx container to distribute the load among the API containers? 
Or are we having multiple workers in a single container and Nginx infixed into the same API container, to balance the load among the workers or processes?

@vivonk what are your thoughts about this. I need suggestions for this implementation 😄

**Comment by JaDogg** [comment]
Gunicorn is a fast WSGI server that can handle connections in multiple processes or workers, we can also use threads in each worker as well. This will allow for a single docker container with backend + gunicorn to process reasonable number of requests. 

So this solves a part of the problem that is to make our backend handle lot of requests. Now we need something that can take the full force of the real world such as nginx to act as a reverse proxy that will connect to multiple Gunicorn powered backends. So if we do this we are theoretically load balancing at 2 levels.

**Comment by kmehant** [comment]
Resolved
