### ISSUE TITLE
[Unit tests] Travis perf issue

### ISSUE THREAD

**Issue by rajikaimal** [scorelab/Bassa#82]
Travis-CI takes a lot of time when running unit tests. This can be avoided to a certain extent by caching dependencies.

**Comment by saisankargochhayat** [comment]
Hey , i have added node modules and bower files to cache . Do you have anything else in mind ? :)

**Comment by rajikaimal** [comment]
#86 solves this.

**Comment by saisankargochhayat** [comment]
Cool :+1:
