### ISSUE TITLE
Get hostnames from environmental variables for Bassa

### ISSUE THREAD

**Issue by kmehant** [scorelab/Bassa#825]
**Describe the bug**
We have to get hostnames using environmental variables to make installation of Bassa easy either from source code or using docker-compose. This change is required for easy K8s deployment.

**Possible solution**
1. Create a python script or use dotenv package to create all required environment variables.
2. Make the required changes in the codebase for it to work.

**Comment by kmehant** [comment]
@JaDogg and @vivonk We require this, what are your thoughts regarding this? 
Moreover, to me, the proper handling of hostnames is required for better container-based deployments.  Please let me know how shall we proceed this, dotenv or python os module?

**Comment by JaDogg** [comment]
If you want environment variables all you need is Python's builtin https://docs.python.org/3/library/os.html#os.environ

**Comment by kmehant** [comment]
> If you want environment variables all you need is Python's builtin https://docs.python.org/3/library/os.html#os.environ

Will send a PR @JaDogg thank you

**Comment by kmehant** [comment]
> If you want environment variables all you need is Python's builtin https://docs.python.org/3/library/os.html#os.environ

Seems like the environmental variables are not persistent using this way as they die after the child process is completed. I think we have to use a shell script to do this and seems like we have to run that script every time to export env variable.

**Comment by JaDogg** [comment]
It depend on how you store the environment variables. Ex: if it's in `~/.bashrc` it will be loaded every time someone (given that their shell == bash) login.  For windows this is in System Properties. 
Environment variables are available to either all processes or to child processes depending on the way you set them.

If you simply want some configuration you can use json (JSON), dotenv (.env file format) or configparser (INI)

**Comment by kmehant** [comment]
> It depend on how you store the environment variables. Ex: if it's in `~/.bashrc` it will be loaded every time someone (given that their shell == bash) login. For windows this is in System Properties.
> Environment variables are available to either all processes or to child processes depending on the way you set them.
> 
> If you simply want some configuration you can use `json` (JSON), `dotenv` (.env file format) or `configparser` (INI).
> 
> 1. json - https://docs.python.org/3/library/json.html
> 2. dotenv - https://pypi.org/project/python-dotenv/
> 3. configparser -  https://docs.python.org/3/library/configparser.html

Thanks @JaDogg seems like dotenv package will be useful to get this done.

**Comment by JaDogg** [comment]
@kmehant I can see we have used .conf file with JSON in Bassa. Maybe we should do the same? @vivonk any ideas?

**Comment by kmehant** [comment]
> @kmehant I can see we have used .conf files (with JSON inside of them) in Bassa. Maybe we should do the same? @vivonk any ideas?

@JaDogg bro True, but shall we have .env files for storing hostnames as it seems apter. As we need them to be as environmental variables to make container deployments easy. what are your thoughts?
@vivonk bro any thoughts?

**Comment by JaDogg** [comment]
OK then env it is :)

**Comment by hv7214** [comment]
@kmehant is it yet to be done ?
