### ISSUE TITLE
[BUG] Start downloads return error

### ISSUE THREAD

**Issue by hv7214** [scorelab/Bassa#872]
**Description**
As Admin, clicking on *Start* results in error. 

**To Reproduce**
1. Login as Admin.
2. Go to *Admin* section.
3. Click on *Start*.
4. See error in terminal.

**Expected behavior**
No error should have been produced and start downloading all files.

**Screenshots**
![Screenshot from 2020-01-28 21-33-42](https://user-images.githubusercontent.com/42354803/73281435-ffb4b200-4215-11ea-89b9-cfa38bea1075.png)

**Desktop**
 - OS: Ubuntu 18.04
 - Browser: Chrome

**Comment by JaDogg** [comment]
@hv7214 Can you add the error message to the ticket as well? Just copy paste full error ! not just the part in screenshot. This will be useful for us in future.

**Comment by hv7214** [comment]
@JaDogg sure

**Comment by kmehant** [comment]
Reason for closing has been mentioned in the referenced PR ;)
