### ISSUE TITLE
Use Blueprints to make the api endpoints look neater and easier to manage

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/Bassa#889]
**Is your feature request related to a problem? Please describe.**
Currently the structure of api's in the server.py file is very unmanageable and very clustered. 
 
**Describe the solution you'd like**
Using blueprints to make the api endpoints look cleaner and well organized.

**Additional context**
I suggest to create a views folder in which the download and user endpoints reside in different files and get registered in the server.py file.

**Comment by carpecodeum** [comment]
@JaDogg @kmehant what are your views on this?

**Comment by JaDogg** [comment]
Good idea.

**Comment by carpecodeum** [comment]
@JaDogg Thank you I will start work on it!
