### ISSUE TITLE
Allow new user only to register with Strong password

### ISSUE THREAD

**Issue by sahandilshan** [scorelab/Bassa#897]
**Is your feature request related to a problem? Please describe.**
In the current implementation, password validations happen at a low level. It accepts the password if it has more than 8 characters. It's not a strong validation checkup.

**Describe the solution you'd like**
Allow users only to register with a High-level password which has mix uppercase, lowercase and numbers, and at least 8 length characters.

**Comment by BLasan** [comment]
@sahandilshan  Can I work on this ?

**Comment by sahandilshan** [comment]
@BLasan, this issue hss been fixed by #898
