### ISSUE TITLE
Pause and Resume buttons are needed with downloading items

### ISSUE THREAD

**Issue by BLasan** [scorelab/Bassa#911]
Currently there's no option to pause and resume a downloading item.Pause and Resume buttons are needed to pause and resume the downloadings for each item. 

![Screenshot from 2020-03-31 18-20-42](https://user-images.githubusercontent.com/43112139/78028376-90298300-737c-11ea-9267-4249be31d3d1.png)

**Comment by BLasan** [comment]
I'll work on this

**Comment by kmehant** [comment]
referencing https://github.com/scorelab/Bassa/pull/912#issuecomment-607014985 :)
