### ISSUE TITLE
Update README on python version and database setup

### ISSUE THREAD

**Issue by Nuwini** [scorelab/Bassa#97]
The steps on how to setup the database for Bassa is not stated in the README file. Also, Bassa seems to work only on Python 3, due to dependency issues. However this is not mentioned in the README. I will send a PR shortly.

**Comment by rajikaimal** [comment]
@Nuwini Installation steps are available, however Python3 support is not mentioned.

**Comment by rajikaimal** [comment]
@Nuwini Yes, Bassa is written with Python 3.

**Comment by Nuwini** [comment]
@rajikaimal Done !

**Comment by Nuwini** [comment]
#99
